
set_property MARK_DEBUG false [get_nets UART_TX_OBUF]
set_property MARK_DEBUG false [get_nets UART_RX_IBUF]
set_property MARK_DEBUG true [get_nets BUFFER_INST/SOF]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_160]]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {BUFFER_INST/U13/cnt[0]} {BUFFER_INST/U13/cnt[1]} {BUFFER_INST/U13/cnt[2]} {BUFFER_INST/U13/cnt[3]} {BUFFER_INST/U13/cnt[4]} {BUFFER_INST/U13/cnt[5]} {BUFFER_INST/U13/cnt[6]} {BUFFER_INST/U13/cnt[7]} {BUFFER_INST/U13/cnt[8]} {BUFFER_INST/U13/cnt[9]} {BUFFER_INST/U13/cnt[10]} {BUFFER_INST/U13/cnt[11]} {BUFFER_INST/U13/cnt[12]} {BUFFER_INST/U13/cnt[13]} {BUFFER_INST/U13/cnt[14]} {BUFFER_INST/U13/cnt[15]} {BUFFER_INST/U13/cnt[16]} {BUFFER_INST/U13/cnt[17]} {BUFFER_INST/U13/cnt[18]} {BUFFER_INST/U13/cnt[19]} {BUFFER_INST/U13/cnt[20]} {BUFFER_INST/U13/cnt[21]} {BUFFER_INST/U13/cnt[22]} {BUFFER_INST/U13/cnt[23]} {BUFFER_INST/U13/cnt[24]} {BUFFER_INST/U13/cnt[25]} {BUFFER_INST/U13/cnt[26]} {BUFFER_INST/U13/cnt[27]} {BUFFER_INST/U13/cnt[28]} {BUFFER_INST/U13/cnt[29]} {BUFFER_INST/U13/cnt[30]} {BUFFER_INST/U13/cnt[31]}]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list BUFFER_INST/SOF]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_160]
