
set_property MARK_DEBUG false [get_nets UART_RX_IBUF]
set_property MARK_DEBUG false [get_nets UART_TX_OBUF]
set_property MARK_DEBUG true [get_nets BUFFER_INST/CLEAR_MEMORY_CONTENT]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI[TDATA][5]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI[TDATA][20]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI[TDATA][1]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI[TDATA][7]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI[TDATA][11]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI[TDATA][13]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI[TDATA][17]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI[TDATA][21]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI[TDATA][25]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI[TDATA][29]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI[TDATA][12]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI[TDATA][16]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI[TDATA][24]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI[TDATA][28]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI[TDATA][22]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI[TDATA][26]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI[TDATA][4]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI[TDATA][6]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI[TDATA][14]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI[TDATA][18]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI[TDATA][30]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI[TDATA][15]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI[TDATA][8]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI[TDATA][0]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI[TDATA][2]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI[TVALID]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI[TDATA][31]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI[TDATA][19]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI[TDATA][27]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI[TDATA][3]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI[TDATA][9]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI[TDATA][23]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI[TDATA][10]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MISO[TREADY]}]

set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][31]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][25]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][20]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][30]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][3]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][21]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][11]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][7]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][5]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][0]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][12]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][1]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][13]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][26]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][8]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][4]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][28]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][16]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][15]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][2]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][14]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][22]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][29]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][18]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][10]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][6]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][9]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][27]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][17]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][23]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][24]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][19]}]

set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][24]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][25]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][28]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][9]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][14]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][4]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][0]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][20]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][22]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][17]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][26]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][16]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][30]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][8]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][6]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][2]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][21]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][5]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][18]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][10]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][13]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][27]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][23]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][12]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][15]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][7]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][11]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][3]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][1]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][29]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][19]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][31]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_160]]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {BUFFER_INST/TX_DATA_MOSI[0]} {BUFFER_INST/TX_DATA_MOSI[1]} {BUFFER_INST/TX_DATA_MOSI[2]} {BUFFER_INST/TX_DATA_MOSI[3]} {BUFFER_INST/TX_DATA_MOSI[4]} {BUFFER_INST/TX_DATA_MOSI[5]} {BUFFER_INST/TX_DATA_MOSI[6]} {BUFFER_INST/TX_DATA_MOSI[7]} {BUFFER_INST/TX_DATA_MOSI[8]} {BUFFER_INST/TX_DATA_MOSI[9]} {BUFFER_INST/TX_DATA_MOSI[10]} {BUFFER_INST/TX_DATA_MOSI[11]} {BUFFER_INST/TX_DATA_MOSI[12]} {BUFFER_INST/TX_DATA_MOSI[13]} {BUFFER_INST/TX_DATA_MOSI[14]} {BUFFER_INST/TX_DATA_MOSI[15]} {BUFFER_INST/TX_DATA_MOSI[16]} {BUFFER_INST/TX_DATA_MOSI[17]} {BUFFER_INST/TX_DATA_MOSI[18]} {BUFFER_INST/TX_DATA_MOSI[19]} {BUFFER_INST/TX_DATA_MOSI[20]} {BUFFER_INST/TX_DATA_MOSI[21]} {BUFFER_INST/TX_DATA_MOSI[22]} {BUFFER_INST/TX_DATA_MOSI[23]} {BUFFER_INST/TX_DATA_MOSI[24]} {BUFFER_INST/TX_DATA_MOSI[25]} {BUFFER_INST/TX_DATA_MOSI[26]} {BUFFER_INST/TX_DATA_MOSI[27]} {BUFFER_INST/TX_DATA_MOSI[28]} {BUFFER_INST/TX_DATA_MOSI[29]} {BUFFER_INST/TX_DATA_MOSI[30]} {BUFFER_INST/TX_DATA_MOSI[31]}]]
connect_debug_port u_ila_0/probe0 [get_nets [list {BUFFER_INST/TX_DATA_MOSI[TDATA][0]} {BUFFER_INST/TX_DATA_MOSI[TDATA][1]} {BUFFER_INST/TX_DATA_MOSI[TDATA][2]} {BUFFER_INST/TX_DATA_MOSI[TDATA][3]} {BUFFER_INST/TX_DATA_MOSI[TDATA][4]} {BUFFER_INST/TX_DATA_MOSI[TDATA][5]} {BUFFER_INST/TX_DATA_MOSI[TDATA][6]} {BUFFER_INST/TX_DATA_MOSI[TDATA][7]} {BUFFER_INST/TX_DATA_MOSI[TDATA][8]} {BUFFER_INST/TX_DATA_MOSI[TDATA][9]} {BUFFER_INST/TX_DATA_MOSI[TDATA][10]} {BUFFER_INST/TX_DATA_MOSI[TDATA][11]} {BUFFER_INST/TX_DATA_MOSI[TDATA][12]} {BUFFER_INST/TX_DATA_MOSI[TDATA][13]} {BUFFER_INST/TX_DATA_MOSI[TDATA][14]} {BUFFER_INST/TX_DATA_MOSI[TDATA][15]} {BUFFER_INST/TX_DATA_MOSI[TDATA][16]} {BUFFER_INST/TX_DATA_MOSI[TDATA][17]} {BUFFER_INST/TX_DATA_MOSI[TDATA][18]} {BUFFER_INST/TX_DATA_MOSI[TDATA][19]} {BUFFER_INST/TX_DATA_MOSI[TDATA][20]} {BUFFER_INST/TX_DATA_MOSI[TDATA][21]} {BUFFER_INST/TX_DATA_MOSI[TDATA][22]} {BUFFER_INST/TX_DATA_MOSI[TDATA][23]} {BUFFER_INST/TX_DATA_MOSI[TDATA][24]} {BUFFER_INST/TX_DATA_MOSI[TDATA][25]} {BUFFER_INST/TX_DATA_MOSI[TDATA][26]} {BUFFER_INST/TX_DATA_MOSI[TDATA][27]} {BUFFER_INST/TX_DATA_MOSI[TDATA][28]} {BUFFER_INST/TX_DATA_MOSI[TDATA][29]} {BUFFER_INST/TX_DATA_MOSI[TDATA][30]} {BUFFER_INST/TX_DATA_MOSI[TDATA][31]}]]
create_debug_port u_ila_0 probe
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][0]} {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][1]} {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][2]} {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][3]} {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][4]} {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][5]} {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][6]} {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][7]} {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][8]} {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][9]} {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][10]} {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][11]} {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][12]} {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][13]} {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][14]} {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][15]} {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][16]} {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][17]} {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][18]} {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][19]} {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][20]} {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][21]} {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][22]} {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][23]} {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][24]} {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][25]} {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][26]} {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][27]} {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][28]} {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][29]} {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][30]} {BUFFER_INST/RX_DATA_MOSI_buf[TDATA][31]}]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list BUFFER_INST/CLEAR_MEMORY_CONTENT]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {BUFFER_INST/RX_DATA_MOSI_buf[TVALID]}]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list BUFFER_INST/TX_DATA_MISO]]

set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_160]
