
set_property MARK_DEBUG false [get_nets UART_TX_OBUF]
set_property MARK_DEBUG false [get_nets UART_RX_IBUF]

set_property MARK_DEBUG true [get_nets BUFFER_INST/WATER_LEVEL]
set_property MARK_DEBUG true [get_nets BUFFER_INST/FALL]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][0]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][10]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][11]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][12]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][13]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][14]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][15]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][16]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][17]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][18]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][19]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][1]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][20]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][21]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][22]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][23]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][24]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][25]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][26]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][27]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][28]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][29]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][2]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][30]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][31]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][3]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][4]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][5]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][6]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][7]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][8]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TDATA][9]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TID][0]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TLAST]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MOSI[TVALID]}]
set_property MARK_DEBUG true [get_nets BUFFER_INST/FSM/CLEAR_MEMORY_CONTENT]
set_property MARK_DEBUG true [get_nets BUFFER_INST/FSM/CONFIG_VALID]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/FSM/BUFFER_MODE[0]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/FSM/BUFFER_MODE[1]}]
set_property MARK_DEBUG false [get_nets BUFFER_INST/MOI]
set_property MARK_DEBUG false [get_nets BUFFER_INST/SOF]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/FSM/NB_SEQUENCE[5]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/FSM/NB_SEQUENCE[7]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/FSM/NB_SEQUENCE[1]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/FSM/NB_SEQUENCE[3]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/FSM/NB_SEQUENCE[0]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/FSM/NB_SEQUENCE[2]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/FSM/NB_SEQUENCE[4]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/FSM/NB_SEQUENCE[6]}]
set_property MARK_DEBUG true [get_nets BUFFER_INST/FSM/NEW_IMAGE_DETECT]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/TX_DATA_MISO[TREADY]}]
set_property MARK_DEBUG false [get_nets {TO_PROC_IN_MISO[TREADY]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/FSM/write_state[2]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/FSM/write_state[0]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/FSM/write_state[1]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/FSM/SEQ_IMG_TOTAL[0]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/FSM/SEQ_IMG_TOTAL[16]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/FSM/SEQ_IMG_TOTAL[19]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/FSM/SEQ_IMG_TOTAL[28]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/FSM/SEQ_IMG_TOTAL[10]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/FSM/SEQ_IMG_TOTAL[8]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/FSM/SEQ_IMG_TOTAL[22]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/FSM/SEQ_IMG_TOTAL[9]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/FSM/SEQ_IMG_TOTAL[15]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/FSM/SEQ_IMG_TOTAL[18]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/FSM/SEQ_IMG_TOTAL[20]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/FSM/SEQ_IMG_TOTAL[21]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/FSM/SEQ_IMG_TOTAL[23]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/FSM/SEQ_IMG_TOTAL[24]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/FSM/SEQ_IMG_TOTAL[1]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/FSM/SEQ_IMG_TOTAL[2]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/FSM/SEQ_IMG_TOTAL[3]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/FSM/SEQ_IMG_TOTAL[4]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/FSM/SEQ_IMG_TOTAL[5]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/FSM/SEQ_IMG_TOTAL[6]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/FSM/SEQ_IMG_TOTAL[7]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/FSM/SEQ_IMG_TOTAL[11]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/FSM/SEQ_IMG_TOTAL[12]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/FSM/SEQ_IMG_TOTAL[13]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/FSM/SEQ_IMG_TOTAL[14]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/FSM/SEQ_IMG_TOTAL[17]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/FSM/SEQ_IMG_TOTAL[25]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/FSM/SEQ_IMG_TOTAL[26]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/FSM/SEQ_IMG_TOTAL[27]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/FSM/SEQ_IMG_TOTAL[29]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/FSM/SEQ_IMG_TOTAL[30]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/FSM/SEQ_IMG_TOTAL[31]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/FSM/NB_SEQUENCE_IN_MEM[4]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/FSM/NB_SEQUENCE_IN_MEM[1]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/FSM/NB_SEQUENCE_IN_MEM[3]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/FSM/NB_SEQUENCE_IN_MEM[7]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/FSM/NB_SEQUENCE_IN_MEM[6]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/FSM/NB_SEQUENCE_IN_MEM[5]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/FSM/NB_SEQUENCE_IN_MEM[0]}]
set_property MARK_DEBUG true [get_nets {BUFFER_INST/FSM/NB_SEQUENCE_IN_MEM[2]}]
set_property MARK_DEBUG false [get_nets BUFFER_INST/FSM/MOI]
set_property MARK_DEBUG true [get_nets BUFFER_INST/FSM/moi_i]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_160]]
set_property port_width 1 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {BUFFER_INST/TX_DATA_MOSI[TID][0]}]]
create_debug_port u_ila_0 probe
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {BUFFER_INST/TX_DATA_MOSI[TDATA][0]} {BUFFER_INST/TX_DATA_MOSI[TDATA][1]} {BUFFER_INST/TX_DATA_MOSI[TDATA][2]} {BUFFER_INST/TX_DATA_MOSI[TDATA][3]} {BUFFER_INST/TX_DATA_MOSI[TDATA][4]} {BUFFER_INST/TX_DATA_MOSI[TDATA][5]} {BUFFER_INST/TX_DATA_MOSI[TDATA][6]} {BUFFER_INST/TX_DATA_MOSI[TDATA][7]} {BUFFER_INST/TX_DATA_MOSI[TDATA][8]} {BUFFER_INST/TX_DATA_MOSI[TDATA][9]} {BUFFER_INST/TX_DATA_MOSI[TDATA][10]} {BUFFER_INST/TX_DATA_MOSI[TDATA][11]} {BUFFER_INST/TX_DATA_MOSI[TDATA][12]} {BUFFER_INST/TX_DATA_MOSI[TDATA][13]} {BUFFER_INST/TX_DATA_MOSI[TDATA][14]} {BUFFER_INST/TX_DATA_MOSI[TDATA][15]} {BUFFER_INST/TX_DATA_MOSI[TDATA][16]} {BUFFER_INST/TX_DATA_MOSI[TDATA][17]} {BUFFER_INST/TX_DATA_MOSI[TDATA][18]} {BUFFER_INST/TX_DATA_MOSI[TDATA][19]} {BUFFER_INST/TX_DATA_MOSI[TDATA][20]} {BUFFER_INST/TX_DATA_MOSI[TDATA][21]} {BUFFER_INST/TX_DATA_MOSI[TDATA][22]} {BUFFER_INST/TX_DATA_MOSI[TDATA][23]} {BUFFER_INST/TX_DATA_MOSI[TDATA][24]} {BUFFER_INST/TX_DATA_MOSI[TDATA][25]} {BUFFER_INST/TX_DATA_MOSI[TDATA][26]} {BUFFER_INST/TX_DATA_MOSI[TDATA][27]} {BUFFER_INST/TX_DATA_MOSI[TDATA][28]} {BUFFER_INST/TX_DATA_MOSI[TDATA][29]} {BUFFER_INST/TX_DATA_MOSI[TDATA][30]} {BUFFER_INST/TX_DATA_MOSI[TDATA][31]}]]
create_debug_port u_ila_0 probe
set_property port_width 3 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {BUFFER_INST/FSM/write_state[0]} {BUFFER_INST/FSM/write_state[1]} {BUFFER_INST/FSM/write_state[2]}]]
create_debug_port u_ila_0 probe
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {BUFFER_INST/U13/cnt[0]} {BUFFER_INST/U13/cnt[1]} {BUFFER_INST/U13/cnt[2]} {BUFFER_INST/U13/cnt[3]} {BUFFER_INST/U13/cnt[4]} {BUFFER_INST/U13/cnt[5]} {BUFFER_INST/U13/cnt[6]} {BUFFER_INST/U13/cnt[7]} {BUFFER_INST/U13/cnt[8]} {BUFFER_INST/U13/cnt[9]} {BUFFER_INST/U13/cnt[10]} {BUFFER_INST/U13/cnt[11]} {BUFFER_INST/U13/cnt[12]} {BUFFER_INST/U13/cnt[13]} {BUFFER_INST/U13/cnt[14]} {BUFFER_INST/U13/cnt[15]} {BUFFER_INST/U13/cnt[16]} {BUFFER_INST/U13/cnt[17]} {BUFFER_INST/U13/cnt[18]} {BUFFER_INST/U13/cnt[19]} {BUFFER_INST/U13/cnt[20]} {BUFFER_INST/U13/cnt[21]} {BUFFER_INST/U13/cnt[22]} {BUFFER_INST/U13/cnt[23]} {BUFFER_INST/U13/cnt[24]} {BUFFER_INST/U13/cnt[25]} {BUFFER_INST/U13/cnt[26]} {BUFFER_INST/U13/cnt[27]} {BUFFER_INST/U13/cnt[28]} {BUFFER_INST/U13/cnt[29]} {BUFFER_INST/U13/cnt[30]} {BUFFER_INST/U13/cnt[31]}]]
create_debug_port u_ila_0 probe
set_property port_width 8 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {BUFFER_INST/FSM/NB_SEQUENCE[0]} {BUFFER_INST/FSM/NB_SEQUENCE[1]} {BUFFER_INST/FSM/NB_SEQUENCE[2]} {BUFFER_INST/FSM/NB_SEQUENCE[3]} {BUFFER_INST/FSM/NB_SEQUENCE[4]} {BUFFER_INST/FSM/NB_SEQUENCE[5]} {BUFFER_INST/FSM/NB_SEQUENCE[6]} {BUFFER_INST/FSM/NB_SEQUENCE[7]}]]
create_debug_port u_ila_0 probe
set_property port_width 32 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {BUFFER_INST/FSM/SEQ_IMG_TOTAL[0]} {BUFFER_INST/FSM/SEQ_IMG_TOTAL[1]} {BUFFER_INST/FSM/SEQ_IMG_TOTAL[2]} {BUFFER_INST/FSM/SEQ_IMG_TOTAL[3]} {BUFFER_INST/FSM/SEQ_IMG_TOTAL[4]} {BUFFER_INST/FSM/SEQ_IMG_TOTAL[5]} {BUFFER_INST/FSM/SEQ_IMG_TOTAL[6]} {BUFFER_INST/FSM/SEQ_IMG_TOTAL[7]} {BUFFER_INST/FSM/SEQ_IMG_TOTAL[8]} {BUFFER_INST/FSM/SEQ_IMG_TOTAL[9]} {BUFFER_INST/FSM/SEQ_IMG_TOTAL[10]} {BUFFER_INST/FSM/SEQ_IMG_TOTAL[11]} {BUFFER_INST/FSM/SEQ_IMG_TOTAL[12]} {BUFFER_INST/FSM/SEQ_IMG_TOTAL[13]} {BUFFER_INST/FSM/SEQ_IMG_TOTAL[14]} {BUFFER_INST/FSM/SEQ_IMG_TOTAL[15]} {BUFFER_INST/FSM/SEQ_IMG_TOTAL[16]} {BUFFER_INST/FSM/SEQ_IMG_TOTAL[17]} {BUFFER_INST/FSM/SEQ_IMG_TOTAL[18]} {BUFFER_INST/FSM/SEQ_IMG_TOTAL[19]} {BUFFER_INST/FSM/SEQ_IMG_TOTAL[20]} {BUFFER_INST/FSM/SEQ_IMG_TOTAL[21]} {BUFFER_INST/FSM/SEQ_IMG_TOTAL[22]} {BUFFER_INST/FSM/SEQ_IMG_TOTAL[23]} {BUFFER_INST/FSM/SEQ_IMG_TOTAL[24]} {BUFFER_INST/FSM/SEQ_IMG_TOTAL[25]} {BUFFER_INST/FSM/SEQ_IMG_TOTAL[26]} {BUFFER_INST/FSM/SEQ_IMG_TOTAL[27]} {BUFFER_INST/FSM/SEQ_IMG_TOTAL[28]} {BUFFER_INST/FSM/SEQ_IMG_TOTAL[29]} {BUFFER_INST/FSM/SEQ_IMG_TOTAL[30]} {BUFFER_INST/FSM/SEQ_IMG_TOTAL[31]}]]
create_debug_port u_ila_0 probe
set_property port_width 8 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {BUFFER_INST/FSM/NB_SEQUENCE_IN_MEM[0]} {BUFFER_INST/FSM/NB_SEQUENCE_IN_MEM[1]} {BUFFER_INST/FSM/NB_SEQUENCE_IN_MEM[2]} {BUFFER_INST/FSM/NB_SEQUENCE_IN_MEM[3]} {BUFFER_INST/FSM/NB_SEQUENCE_IN_MEM[4]} {BUFFER_INST/FSM/NB_SEQUENCE_IN_MEM[5]} {BUFFER_INST/FSM/NB_SEQUENCE_IN_MEM[6]} {BUFFER_INST/FSM/NB_SEQUENCE_IN_MEM[7]}]]
create_debug_port u_ila_0 probe
set_property port_width 2 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {BUFFER_INST/FSM/BUFFER_MODE[0]} {BUFFER_INST/FSM/BUFFER_MODE[1]}]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list BUFFER_INST/FSM/CLEAR_MEMORY_CONTENT]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list BUFFER_INST/FSM/CONFIG_VALID]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list BUFFER_INST/FALL]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list BUFFER_INST/FSM/moi_i]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list BUFFER_INST/FSM/NEW_IMAGE_DETECT]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list {BUFFER_INST/TX_DATA_MISO[TREADY]}]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list {BUFFER_INST/TX_DATA_MOSI[TLAST]}]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list {BUFFER_INST/TX_DATA_MOSI[TVALID]}]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list BUFFER_INST/WATER_LEVEL]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_160]
