/**
 * @file tel2000_param.h
 * Tel2000 axi port address map.
 *
 * This file declares the address of every axi lite port.
 * This is automaticly generated by tel_extract_param.tcl
 *
 * $Rev$
 * $Author$
 * $Date$
 * $Id$
 * $URL$
 *
 * (c) Copyright 2014 Telops Inc.
 */
 
#ifndef TEL2000_PARAM_H
#define TEL2000_PARAM_H
 
 /**
 * AXI PORT declaration
 */
/* Definitions for peripheral TEL_AXIL_BUF */
#define TEL_PAR_TEL_AXIL_BUF_BASEADDR 0x44A10000
#define TEL_PAR_TEL_AXIL_BUF_HIGHADDR 0x44A1FFFF 

/* Definitions for peripheral TEL_AXIL_BUF_TABLE */
#define TEL_PAR_TEL_AXIL_BUF_TABLE_BASEADDR 0x44A30000
#define TEL_PAR_TEL_AXIL_BUF_TABLE_HIGHADDR 0x44A3FFFF 

/* Definitions for peripheral TEL_AXIL_MEM_OUT */
#define TEL_PAR_TEL_AXIL_MEM_OUT_BASEADDR 0x80000000
#define TEL_PAR_TEL_AXIL_MEM_OUT_HIGHADDR 0xFFFFFFFF 

/* Definitions for peripheral TEL_AXIL_MGT */
#define TEL_PAR_TEL_AXIL_MGT_BASEADDR 0x44A20000
#define TEL_PAR_TEL_AXIL_MGT_HIGHADDR 0x44A2FFFF 

#endif // TEL2000_PARAM_H
