/**
 * @file tel2000_param.h
 * Tel2000 axi port address map.
 *
 * This file declares the address of every axi lite port.
 * This is automaticly generated by tel_extract_param.tcl
 *
 * $Rev$
 * $Author$
 * $Date$
 * $Id$
 * $URL$
 *
 * (c) Copyright 2014 Telops Inc.
 */
 
#ifndef TEL2000_PARAM_H
#define TEL2000_PARAM_H

/**
* Clock declaration
*/
#define CLK_DATA_FREQ_HZ 100000000
#define CLK_FLOW_CTRLER_FREQ_HZ 85000000
#define CLK_MB_FREQ_HZ 100000000
#define CLK_MGT_INIT_FREQ_HZ 50000000

/**
* AXI PORT declaration
*/
/* Definitions for peripheral TEL_dimm0_ctrl_memaddr */
#define TEL_PAR_TEL_dimm0_ctrl_memaddr_BASEADDR 0x0000000000000000
#define TEL_PAR_TEL_dimm0_ctrl_memaddr_HIGHADDR 0x00000003FFFFFFFF 

/* Definitions for peripheral TEL_dimm1_ctrl_memaddr */
#define TEL_PAR_TEL_dimm1_ctrl_memaddr_BASEADDR 0x0000000400000000
#define TEL_PAR_TEL_dimm1_ctrl_memaddr_HIGHADDR 0x00000007FFFFFFFF 

/* Definitions for peripherals connected to TEL_AXIL_PERIPHERAL */
#define AXIL_DEMUX_SLAVE_ADDR_WIDTH       14
#define XPAR_M_BUFFERING_CTRL_BASEADDR    (XPAR_AXIL_PERIPHERAL_BASEADDR + (0 << AXIL_DEMUX_SLAVE_ADDR_WIDTH))
#define XPAR_M_BUF_TABLE_BASEADDR         (XPAR_AXIL_PERIPHERAL_BASEADDR + (1 << AXIL_DEMUX_SLAVE_ADDR_WIDTH))
#define TEL_PAR_TEL_UNUSED_BASEADDR       (XPAR_AXIL_PERIPHERAL_BASEADDR + (2 << AXIL_DEMUX_SLAVE_ADDR_WIDTH))
#define XPAR_MGT_CTRL_BASEADDR            (XPAR_AXIL_PERIPHERAL_BASEADDR + (3 << AXIL_DEMUX_SLAVE_ADDR_WIDTH))

#endif // TEL2000_PARAM_H
